## Sector: Aluminium

### Sub-Sector: Secondary Aluminium

| S. No. | Obligated Entity (Name, Address and State)                                                                | Registration Number | Baseline Equivalent Major Product Output 2023–24 (Tonne) | Baseline GHG Emission Intensity 2023–24 (tCO₂ equivalent / Tonne of equivalent product) | Compliance Year 2025–26 (tCO₂ equivalent / Tonne) | Compliance Year 2026–27 (tCO₂ equivalent / Tonne) |
| ------ | --------------------------------------------------------------------------------------------------------- | ------------------- | -------------------------------------------------------- | --------------------------------------------------------------------------------------- | ------------------------------------------------- | ------------------------------------------------- |
| 1      | Hindalco Industries Limited, Plot No. 2, MIDC Taloja, A.V, Navi Mumbai, Dist Raigad, Maharashtra – 410208 | ALMOE014MH          | 46845                                                    | 1.3386                                                                                  | 1.3304                                            | 1.2800                                            |
| 2      | Hirakud FRP Plant, Hindalco Industries Ltd, Hirakud, Sambalpur, Odisha – 768016                           | ALMOE015OD          | 103292                                                   | 1.1650                                                                                  | 1.1588                                            | 1.1208                                            |
| 3      | Hindalco Industries Limited – Mouda Works, Ramtek Road, Dahali, Mouda Dist, Maharashtra – 441104          | ALMOE016MH          | 27265                                                    | 1.4372                                                                                  | 1.4277                                            | 1.3696                                            |

---

## Sector: Petroleum Refinery

| S. No. | Obligated Entity (Name, Address and State)                                                                                         | Registration Number | Baseline Crude Throughput 2023–24 (MBBLS) | NRGF Factor | Baseline GHG Emission Intensity 2023–24 (tCO₂ equivalent / MBBLS / NRGF) | Compliance Year 2025–26 | Compliance Year 2026–27 |
| ------ | ---------------------------------------------------------------------------------------------------------------------------------- | ------------------- | ----------------------------------------- | ----------- | ------------------------------------------------------------------------ | ----------------------- | ----------------------- |
| 1      | Bharat Petroleum Corporation Ltd – Bina Refinery, Post BPCL Residential Complex, Bina, Dist. Sagar, Madhya Pradesh – 470124        | REFOE001MP          | 51418                                     | 8.3285      | 6.6553                                                                   | 6.6172                  | 6.3846                  |
| 2      | Bharat Petroleum Corporation Ltd – Kochi Refinery, Ambalamugal, Kochi, Kerala – 682302                                             | REFOE002KL          | 127757                                    | 6.9921      | 4.5652                                                                   | 4.5501                  | 4.4583                  |
| 3      | Bharat Petroleum Corporation Ltd – Mumbai Refinery, Ramakrishna Chemburkar Marg, Mahul, Chembur East, Mumbai, Maharashtra – 400074 | REFOE003MH          | 115521                                    | 5.0400      | 4.4095                                                                   | 4.3918                  | 4.2843                  |
| 4      | Chennai Petroleum Corporation Ltd – Manali Refinery, Manali, Chennai, Tamil Nadu – 600068                                          | REFOE004TN          | 85085                                     | 6.0477      | 5.8659                                                                   | 5.8373                  | 5.6635                  |
| 5      | Hindustan Petroleum Corp Ltd, Mumbai Refinery, R.C. Marg, Mahul, Chembur East, Mumbai, Maharashtra – 400074                        | REFOE005MH          | 71975                                     | 6.1096      | 5.9125                                                                   | 5.8763                  | 5.6549                  |
| 6      | Hindustan Petroleum Corporation Ltd – Visakh Refinery, Malkapuram, Visakhapatnam, Andhra Pradesh – 530011                          | REFOE006AP          | 93854                                     | 5.0874      | 6.0704                                                                   | 6.0320                  | 5.7970                  |
| 7      | HPCL – Mittal Energy Limited (Guru Gobind Singh Refinery), Kanakwal Urf Rattangarh, Punjab – 151301                                | REFOE007PB          | 90673                                     | 8.4513      | 5.7663                                                                   | 5.7447                  | 5.6135                  |
| 8      | Indian Oil Corporation Limited – Barauni Refinery, Barauni–Kanpur Pipeline, Begusarai, Bihar – 851114                              | REFOE008BR          | 49463                                     | 6.0693      | 5.8350                                                                   | 5.8086                  | 5.6485                  |
| 9      | Indian Oil Corporation Limited – Bongaigaon Refinery, Assam – 783385                                                               | REFOE009AS          | 22350                                     | 6.0686      | 7.9764                                                                   | 7.9285                  | 7.6355                  |
| 10     | Indian Oil Corporation Limited – Gujarat Refinery, Jawahar Nagar, Vadodara, Gujarat – 391320                                       | REFOE011GJ          | 109915                                    | 6.3714      | 7.2409                                                                   | 7.1895                  | 6.8744                  |
| 11     | Indian Oil Corporation Limited – Haldia Refinery, Purba Medinipur, West Bengal – 721605                                            | REFOE013WB          | 58457                                     | 6.6304      | 5.5541                                                                   | 5.5242                  | 5.3415                  |
| 12     | Indian Oil Corporation Limited – Mathura Refinery, Mathura, Uttar Pradesh – 281005                                                 | REFOE014UP          | 67665                                     | 5.7430      | 9.1348                                                                   | 9.0607                  | 8.6049                  |
| 13     | Indian Oil Corporation Limited – Panipat Refinery, Haryana – 132140                                                                | REFOE015HR          | 105802                                    | 6.3174      | 7.8403                                                                   | 7.7858                  | 7.4518                  |
| 14     | Indian Oil Corporation Limited – Digboi Refinery, Tinsukia, Assam – 786171                                                         | REFOE010AS          | 5077                                      | 7.0643      | 5.3245                                                                   | 5.2976                  | 5.1336                  |
| 15     | Indian Oil Corporation Limited – Paradeep Refinery, Jagatsinghapur, Odisha – 754142                                                | REFOE016OD          | 108991                                    | 7.9122      | 5.6282                                                                   | 5.6076                  | 5.4826                  |
| 16     | Indian Oil Corporation Limited – Guwahati Refinery, Noonmati, Assam – 781020                                                       | REFOE012AS          | 7326                                      | 5.8483      | 5.3852                                                                   | 5.3630                  | 5.2279                  |
| 17     | Mangalore Refinery and Petrochemicals Ltd, Kuthethoor, Karnataka – 575030                                                          | REFOE017KA          | 120200                                    | 7.3600      | 5.7189                                                                   | 5.6885                  | 5.5029                  |
| 18     | Nayara Refinery Site, Jamnagar, Gujarat – 361305                                                                                   | REFOE018GJ          | 144171                                    | 8.2760      | 5.1119                                                                   | 5.0887                  | 4.9477                  |
| 19     | Numaligarh Refinery Ltd, Golaghat, Assam – 785699                                                                                  | REFOE019AS          | 17671                                     | 7.9741      | 5.4854                                                                   | 5.4637                  | 5.3324                  |
| 20     | Reliance Industries Ltd (DTA), Village Meghhpar/Padana, Jamnagar, Gujarat – 361280                                                 | REFOE020GJ          | 241380                                    | 8.5035      | 4.9877                                                                   | 4.9723                  | 4.8793                  |
| 21     | Reliance Industries Ltd (SEZ), Jamnagar SEZ Unit, Gujarat – 361140                                                                 | REFOE021GJ          | 258662                                    | 11.0441     | 4.7830                                                                   | 4.7723                  | 4.7079                  |

---

## Sector: Petrochemical Units (Gas / Naphtha Crackers or Both)

| S. No. | Obligated Entity (Name, Address and State)                                                 | Registration Number | Baseline Equivalent Major Product Output 2023–24 (Tonne) | Baseline GHG Emission Intensity 2023–24 (tCO₂ equivalent / Tonne of equivalent product) | Compliance Year 2025–26 | Compliance Year 2026–27 |
| ------ | ------------------------------------------------------------------------------------------ | ------------------- | -------------------------------------------------------- | --------------------------------------------------------------------------------------- | ----------------------- | ----------------------- |
| 1      | Indian Oil Corporation Limited, Panipat Refinery & Petrochemical Complex, Panipat – 132140 | PCOE001HR           | 2785937                                                  | 0.8566                                                                                  | 0.8523                  | 0.8262                  |
| 2      | Haldia Petrochemicals Limited, Haldia, West Bengal – 721602                                | PCOE002WB           | 1530961                                                  | 0.9112                                                                                  | 0.9067                  | 0.8789                  |
| 3      | Reliance Industries Ltd., Vadodara Manufacturing Division, Gujarat – 391346                | PCOE003GJ           | 565262                                                   | 1.3218                                                                                  | 1.3152                  | 1.2749                  |
| 4      | Reliance Industries Limited, Hazira Manufacturing Division, Surat, Gujarat – 394510        | PCOE004GJ           | 4634895                                                  | 0.8731                                                                                  | 0.8687                  | 0.8421                  |
| 5      | GAIL (India) Limited, Petrochemical Complex, Pata, Uttar Pradesh – 206241                  | PCOE005UP           | 865591                                                   | 1.1451                                                                                  | 1.1394                  | 1.1045                  |
| 6      | Reliance Industries Limited, Nagothane Manufacturing Division, Maharashtra – 402125        | PCOE006MH           | 700115                                                   | 1.0062                                                                                  | 1.0011                  | 0.9705                  |
| 7      | Reliance Industries Ltd., Dahej Manufacturing Division, Bharuch, Gujarat – 392130          | PCOE007GJ           | 3357493                                                  | 0.6513                                                                                  | 0.6480                  | 0.6282                  |
| 8      | Brahmaputra Cracker and Polymer Limited, Dibrugarh, Assam – 786006                         | PCOE008AS           | 294429                                                   | 1.3303                                                                                  | 1.3236                  | 1.2831                  |
| 9      | ONGC Petro additions Limited, Dahej SEZ, Gujarat – 392130                                  | PCOE009GJ           | 1783547                                                  | 1.1378                                                                                  | 1.1321                  | 1.0974                  |
| 10     | Reliance Industries Limited, Jamnagar Manufacturing Division, Gujarat – 361142             | PCOE010GJ           | 3281702                                                  | 0.9447                                                                                  | 0.9399                  | 0.9112                  |
| 11     | HPCL–Mittal Energy Limited – Guru Gobind Singh Refinery, Bathinda, Punjab – 151301         | PCOE011PB           | 1400791                                                  | 1.6474                                                                                  | 1.6392                  | 1.5890                  |

---

# Sector: Textile

## Sub-Sector: Spinning

| S. No. | Obligated Entity (Name, Address and State)                                     | Registration Number | Baseline Equivalent Major Product Output 2023–24 (Tonne) | Baseline GHG Emission Intensity 2023–24 (tCO₂ eq / Tonne) | Compliance Year 2025–26 | Compliance Year 2026–27 |
| ------ | ------------------------------------------------------------------------------ | ------------------- | -------------------------------------------------------- | --------------------------------------------------------- | ----------------------- | ----------------------- |
| 1      | L.S. Mills Ltd., ‘B’ Unit, Cumbum Road, Theni, Tamil Nadu                      | TXTOE001TN          | 13586                                                    | 0.1667                                                    | 0.1667                  | 0.1667                  |
| 2      | Madura Coats Pvt. Ltd., Aladiyur, Tirunelveli, Tamil Nadu – 627422             | TXTOE002TN          | 21406                                                    | 0.4355                                                    | 0.4352                  | 0.4329                  |
| 3      | Aruppukottai Sri Jaya Vilas Ltd., Malakadamangalam, Tamil Nadu – 626129        | TXTOE003TN          | 8393                                                     | 0.7714                                                    | 0.7703                  | 0.7635                  |
| 4      | Space Textiles Pvt. Ltd., Avinashi, Tamil Nadu – 641037                        | TXTOE004TN          | 8907                                                     | 1.2484                                                    | 1.2455                  | 1.2277                  |
| 5      | Sangam (India) Ltd., Spinning Unit-I, Bhilwara, Rajasthan – 311001             | TXTOE005RJ          | 36451                                                    | 1.2765                                                    | 1.2734                  | 1.2549                  |
| 6      | Ambika Cotton Mills Ltd., Dindigul, Tamil Nadu – 624308                        | TXTOE006TN          | 13544                                                    | 1.2915                                                    | –                       | 1.2693                  |
| 7      | Trident Ltd. (Yarn Division), Barnala, Punjab – 148101                         | TXTOE007PB          | 19397                                                    | 5.4436                                                    | 5.3877                  | 5.0415                  |
| 8      | Bannariamman Spinning Mills Ltd., Trichy–Dindigul Highway, Tamil Nadu – 624803 | TXTOE008TN          | 13360                                                    | 1.4850                                                    | 1.4809                  | 1.4556                  |
| 9      | KPR Mills-II, Coimbatore, Tamil Nadu – 641407                                  | TXTOE009TN          | 21723                                                    | 1.5768                                                    | 1.5721                  | 1.5437                  |
| 10     | Vardhman Yarns & Threads Ltd., Hoshiarpur, Punjab – 146001                     | TXTOE010PB          | 19289                                                    | 1.9316                                                    | 1.9246                  | 1.8819                  |
| 11     | Chenab Textile Mills (Sutlej Textiles), Kathua, Jammu & Kashmir – 184102       | TXTOE011JK          | 57246                                                    | 3.2559                                                    | 3.2359                  | 3.1136                  |
| 12     | Fiotex Cotspin Pvt. Ltd., Jamnagar, Gujarat – 360110                           | TXTOE012GJ          | 9682                                                     | 2.0500                                                    | –                       | 1.9939                  |
| 13     | KPR Mills, Neelambur, Coimbatore, Tamil Nadu – 641062                          | TXTOE013TN          | 11249                                                    | 2.0656                                                    | –                       | 2.0087                  |
| 14     | Omax Cotspin Pvt. Ltd., Surendranagar, Gujarat – 363320                        | TXTOE014GJ          | 10928                                                    | 2.2680                                                    | –                       | 2.1993                  |
| 15     | KPR Mills-I, Coimbatore, Tamil Nadu – 641659                                   | TXTOE015TN          | 25765                                                    | 2.2690                                                    | 2.2593                  | 2.2002                  |
| 16     | Suryalatha Spinning Mills, Nagarkurnool, Telangana – 509320                    | TXTOE016TS          | 12249                                                    | 2.3573                                                    | –                       | 2.2831                  |
| 17     | Suryalakshmi Cotton Mills Ltd., Telangana – 509321                             | TXTOE017TS          | 8545                                                     | 2.4583                                                    | –                       | 2.3775                  |
| 18     | Vasantha Industries Ltd., Guntur, Andhra Pradesh – 522233                      | TXTOE018AP          | 11247                                                    | 2.4833                                                    | 2.4717                  | 2.4009                  |
| 19     | Sudiva Spinners Pvt. Ltd., Bhilwara, Rajasthan – 311024                        | TXTOE019RJ          | 24103                                                    | 2.4845                                                    | –                       | 2.4020                  |
| 20     | DCM Textiles (DCM Nouvelle Ltd.), Hisar, Haryana                               | TXTOE020HR          | 23912                                                    | 2.5093                                                    | 2.4974                  | 2.4251                  |
| 21     | RSWM Ltd., Gulabpura, Bhilwara, Rajasthan                                      | TXTOE021RJ          | 40989                                                    | 2.5187                                                    | 2.5067                  | 2.4339                  |

---

## Sector: Textile

### Sub-Sector: Spinning (continued)

| S. No. | Obligated Entity (Name, Address and State)                    | Registration Number | Baseline Equivalent Major Product Output 2023–24 (Tonne) | Baseline GHG Emission Intensity 2023–24 (tCO₂ eq / Tonne) | Compliance Year 2025–26 | Compliance Year 2026–27 |
| ------ | ------------------------------------------------------------- | ------------------- | -------------------------------------------------------- | --------------------------------------------------------- | ----------------------- | ----------------------- |
| 22     | S T Cottex Exports Pvt. Ltd., Machhiwara, Ludhiana, Punjab    | TXTOE022PB          | 43707                                                    | 2.5747                                                    | 2.5622                  | 2.4860                  |
| 23     | Aarti International Ltd., Ramgadh, Ludhiana, Punjab           | TXTOE023PB          | 30025                                                    | 2.6790                                                    | 2.6655                  | 2.5830                  |
| 24     | Orient Syntex (APM Industries Ltd.), Bhiwadi, Rajasthan       | TXTOE024RJ          | 13322                                                    | 2.6790                                                    | 2.6655                  | 2.5830                  |
| 25     | Sportking Industries Ltd., Jeeda, Bathinda, Punjab            | TXTOE025PB          | 50393                                                    | 2.6925                                                    | 2.6788                  | 2.5954                  |
| 26     | Deepak Spinners Ltd., Baddi, Himachal Pradesh                 | TXTOE026HP          | 10973                                                    | 2.7000                                                    | 2.6863                  | 2.6025                  |
| 27     | Reliance Chemotex Industries Ltd., Kanpur, Udaipur, Rajasthan | TXTOE027RJ          | 12957                                                    | 2.8224                                                    | 2.8074                  | 2.7157                  |
| 28     | Sitaram Spinners Pvt. Ltd., Siddipet, Telangana               | TXTOE028TS          | 13375                                                    | 2.8433                                                    | 2.8281                  | 2.7350                  |
| 29     | Nitin Spinners Ltd., Hamirgadh, Bhilwara, Rajasthan           | TXTOE029RJ          | 55218                                                    | 2.8553                                                    | 2.8399                  | 2.7461                  |
| 30     | Vardhman Spinning & General Mills, Ludhiana, Punjab           | TXTOE030PB          | 13572                                                    | 2.9627                                                    | 2.9462                  | 2.8450                  |
| 31     | Sangam (India) Ltd., Spinning Unit-II, Bhilwara, Rajasthan    | TXTOE031RJ          | 29416                                                    | 2.9823                                                    | 2.9655                  | 2.8631                  |
| 32     | RSWM Ltd., Lodha, Banswara, Rajasthan                         | TXTOE032RJ          | 25298                                                    | 3.0082                                                    | 2.9911                  | 2.8869                  |
| 33     | Arisht Spinning Mills, Baddi, Himachal Pradesh                | TXTOE033HP          | 17561                                                    | 3.0792                                                    | 3.0613                  | 2.9520                  |
| 34     | Nahar Spinning Mills Ltd., Mandideep, Madhya Pradesh          | TXTOE034MP          | 23454                                                    | 3.1070                                                    | 3.0888                  | 2.9775                  |
| 35     | Vardhman Yarn, Mandideep, Madhya Pradesh                      | TXTOE035MP          | 64243                                                    | 3.1582                                                    | 3.1394                  | 3.0244                  |
| 36     | Ravali Spinners Pvt. Ltd., West Godavari, Andhra Pradesh      | TXTOE036AP          | 9857                                                     | 3.1711                                                    | 3.1521                  | 3.0362                  |
| 37     | Winsome Textile Industries Ltd., Baddi, Himachal Pradesh      | TXTOE037HP          | 15757                                                    | 3.1878                                                    | 3.1686                  | 3.0515                  |
| 38     | Nandan Denim Ltd., Kheda, Gujarat                             | TXTOE038GJ          | 6784                                                     | 3.2043                                                    | –                       | 3.0666                  |
| 39     | RSWM Ltd., Rishabhdev, Udaipur, Rajasthan                     | TXTOE039RJ          | 8532                                                     | 3.2267                                                    | 3.2071                  | 3.0870                  |
| 40     | Rajasthan Textiles Mills, Bhawani Mandi, Rajasthan            | TXTOE040RJ          | 24274                                                    | 3.4309                                                    | 3.4087                  | 3.2727                  |
| 41     | Vardhman Spinning Mills, Baddi, Himachal Pradesh              | TXTOE041HP          | 9661                                                     | 3.4388                                                    | 3.4165                  | 3.2799                  |
| 42     | Anant Spinning Mills, Mandideep, Madhya Pradesh               | TXTOE042MP          | 21739                                                    | 3.4751                                                    | 3.4523                  | 3.3129                  |
| 43     | Auro Spinning Mills, Baddi, Himachal Pradesh                  | TXTOE043HP          | 12606                                                    | 3.5232                                                    | 3.4998                  | 3.3564                  |
| 44     | Sportking Synthetics, Ludhiana, Punjab                        | TXTOE044PB          | 9514                                                     | 3.5837                                                    | 3.5595                  | 3.4110                  |
| 45     | RSWM Ltd., Ringas, Rajasthan                                  | TXTOE045RJ          | 8831                                                     | 3.5899                                                    | 3.5656                  | 3.4167                  |
| 46     | Nahar Spinning Mills Ltd. (Rishab Unit), Ludhiana, Punjab     | TXTOE046PB          | 15128                                                    | 3.6280                                                    | 3.6032                  | 3.4510                  |
| 47     | Nahar Spinning Mills Ltd. (Unit-II), Dappar, Punjab           | TXTOE047PB          | 7074                                                     | 3.6434                                                    | 3.6184                  | 3.4650                  |
| 48     | GTN Engineering (India) Ltd., Sangareddy, Telangana           | TXTOE048TS          | 8120                                                     | 3.6552                                                    | –                       | 3.4756                  |
| 49     | Indo Count Industries Ltd., Kolhapur, Maharashtra             | TXTOE049MH          | 7226                                                     | 3.6995                                                    | 3.6737                  | 3.5154                  |
| 50     | RSWM Ltd., Mandpam, Bhilwara, Rajasthan                       | TXTOE050RJ          | 13355                                                    | 3.7416                                                    | 3.7152                  | 3.5532                  |
| 51     | Birla Textile Mills, Baddi, Himachal Pradesh                  | TXTOE051HP          | 15035                                                    | 3.7914                                                    | 3.7643                  | 3.5980                  |
| 52     | Nahar Fibers, Sangrur, Punjab                                 | TXTOE052PB          | 21671                                                    | 3.8745                                                    | 3.8462                  | 3.6724                  |
| 53     | Shivraj Spinning Mills (P) Ltd., Dindigul, Tamil Nadu         | TXTOE053TN          | 8325                                                     | 3.9556                                                    | 3.9261                  | 3.7449                  |
| 54     | Gimatex Industries Pvt. Ltd., Wardha, Maharashtra             | TXTOE054MH          | 11347                                                    | 4.2014                                                    | 4.1681                  | 3.9634                  |
| 55     | Alok Industries Ltd., Silvassa, Dadra & Nagar Haveli          | TXTOE055DN          | 42031                                                    | 4.4881                                                    | 4.4501                  | 4.2161                  |
| 56     | Nahar Industrial Enterprises Ltd., Mohali, Punjab             | TXTOE056PB          | 5206                                                     | 4.7040                                                    | 4.6623                  | 4.4049                  |
| 57     | Shri Ramalinga Mills Ltd., Ammapettai, Tamil Nadu             | TXTOE057TN          | 9169                                                     | 4.7347                                                    | 4.6924                  | 4.4316                  |
| 58     | Nahar Industrial Enterprises Ltd., Bhiwadi, Rajasthan         | TXTOE058RJ          | 5860                                                     | 4.8126                                                    | 4.7689                  | 4.4994                  |
| 59     | Arihant Spinning Mills, Malerkotla, Punjab                    | TXTOE059PB          | 12929                                                    | 4.9056                                                    | 4.8602                  | 4.5799                  |
| 60     | Banswara Syntex Ltd., Banswara, Rajasthan                     | TXTOE060RJ          | 10038                                                    | 5.9339                                                    | 5.8675                  | 5.4550                  |

---

## Sector: Textile

### Sub-Sector: Processing

| S. No. | Obligated Entity (Name, Address and State)                               | Registration Number | Baseline Equivalent Major Product Output 2023–24 (Tonne) | Baseline GHG Emission Intensity 2023–24 (tCO₂ eq / Tonne) | Compliance Year 2025–26 | Compliance Year 2026–27 |
| ------ | ------------------------------------------------------------------------ | ------------------- | -------------------------------------------------------- | --------------------------------------------------------- | ----------------------- | ----------------------- |
| 61     | BSL Limited (Processing Division), Mandpam, Bhilwara, Rajasthan – 311001 | TXTOE061RJ          | 11142                                                    | 0.6307                                                    | 0.6301                  | 0.6262                  |
| 62     | Sona Selection India Ltd., Hamirgarh, Bhilwara, Rajasthan – 311025       | TXTOE062RJ          | 16755                                                    | 1.1814                                                    | –                       | 1.1656                  |
| 63     | Rolex Processors Pvt. Ltd., Gangapur Road, Bhilwara, Rajasthan – 311802  | TXTOE063RJ          | 24459                                                    | 1.5893                                                    | 1.5853                  | 1.5607                  |
| 64     | Sona Processors I Ltd., Bhilwara, Rajasthan – 311001                     | TXTOE064RJ          | 28117                                                    | 1.9853                                                    | 1.9790                  | 1.9406                  |
| 65     | Banswara Syntex Ltd. (Processing Division), Banswara, Rajasthan – 327001 | TXTOE065RJ          | 8248                                                     | 7.7541                                                    | 7.6573                  | 7.0536                  |
| 66     | Noble Tex Industries Ltd., Surat, Gujarat – 394315                       | TXTOE066GJ          | 15635                                                    | 2.0862                                                    | 2.0792                  | 2.0368                  |
| 67     | Kumar Cotton Mills Pvt. Ltd., Ahmedabad, Gujarat – 382402                | TXTOE067GJ          | 27352                                                    | 2.3880                                                    | 2.3788                  | 2.3231                  |
| 68     | AK Spintex Ltd., Bhilwara, Rajasthan                                     | TXTOE068RJ          | 17166                                                    | 2.5265                                                    | 2.5162                  | 2.4539                  |
| 69     | Janki Corp Ltd., Bhilwara, Rajasthan                                     | TXTOE069RJ          | 21645                                                    | 2.5469                                                    | 2.5365                  | 2.4731                  |
| 70     | Ronak Processors (P) Ltd., Bhilwara, Rajasthan                           | TXTOE070RJ          | 9244                                                     | 2.5664                                                    | 2.5558                  | 2.4914                  |
| 71     | TPL Industries Ltd., Bhilwara, Rajasthan – 311001                        | TXTOE071RJ          | 14598                                                    | 2.5909                                                    | 2.5801                  | 2.5145                  |
| 72     | Swastika Suitings Ltd., Bhilwara, Rajasthan                              | TXTOE072RJ          | 7514                                                     | 2.6033                                                    | 2.5924                  | 2.5261                  |
| 73     | KPR Mills Ltd. – Processing Mill, Erode, Tamil Nadu – 638052             | TXTOE073TN          | 23229                                                    | 2.6613                                                    | –                       | 2.5806                  |
| 74     | Kanchan India Ltd., Bhilwara, Rajasthan                                  | TXTOE074RJ          | 42435                                                    | 2.6711                                                    | 2.6596                  | 2.5898                  |
| 75     | Ranjan Processors (Ranjan Polyester Ltd.), Bhilwara, Rajasthan           | TXTOE075RJ          | 13618                                                    | 2.7061                                                    | 2.6943                  | 2.6227                  |
| 76     | S. P. Apparels, Erode, Tamil Nadu – 638052                               | TXTOE076TN          | 5455                                                     | 2.8130                                                    | 2.8003                  | 2.7228                  |
| 77     | Sulzer Processors Pvt. Ltd., Mandal, Bhilwara, Rajasthan                 | TXTOE077RJ          | 15192                                                    | 2.8411                                                    | 2.8281                  | 2.7491                  |
| 78     | Sarvodaya India Ltd., Bhilwara, Rajasthan – 311001                       | TXTOE078RJ          | 16110                                                    | 2.9161                                                    | 2.9024                  | 2.8191                  |
| 79     | Puja Spintex Pvt. Ltd., Bhilwara, Rajasthan – 311001                     | TXTOE079RJ          | 14437                                                    | 4.1857                                                    | –                       | 3.9800                  |
| 80     | Anant Syntex Ltd., Bhilwara, Rajasthan – 311001                          | TXTOE080RJ          | 15907                                                    | 3.0381                                                    | 3.0233                  | 2.9327                  |
| 81     | Durga Processors Pvt. Ltd., Surat, Gujarat – 394305                      | TXTOE081GJ          | 28572                                                    | 3.5389                                                    | 3.5188                  | 3.3956                  |
| 82     | Sutlej Textiles & Industries Ltd., Valsad, Gujarat – 396105              | TXTOE082GJ          | 10750                                                    | 3.7187                                                    | –                       | 3.5604                  |
| 83     | Anjani Synthetic Ltd., Ahmedabad, Gujarat – 382405                       | TXTOE083GJ          | 12278                                                    | 4.2465                                                    | –                       | 4.0396                  |
| 84     | Creative Textile Mills Pvt. Ltd., Vapi, Gujarat – 396195                 | TXTOE084GJ          | 10958                                                    | 4.4312                                                    | 4.3996                  | 4.2057                  |
| 85     | Shahi Knits Pvt. Ltd., Perundurai, Tamil Nadu – 638052                   | TXTOE085TN          | 6209                                                     | 6.3076                                                    | 6.2436                  | 5.8470                  |
| 86     | Alok Industry – Vapi (Integrated Textile Solution), Gujarat – 396191     | TXTOE086GJ          | 23633                                                    | 7.0645                                                    | 6.9842                  | 6.4848                  |
| 87     | Jindal Creation Ltd., Ahmedabad, Gujarat – 382405                        | TXTOE087GJ          | 3596                                                     | 7.3636                                                    | –                       | 6.7329                  |
| 88     | Bindal Silk Mills Pvt. Ltd., Surat, Gujarat – 394327                     | TXTOE088GJ          | 5767                                                     | 7.6270                                                    | 7.5334                  | 6.9496                  |
| 89     | G. M. Syntex Pvt. Ltd., Tarapur, Maharashtra – 401501                    | TXTOE089MH          | 5774                                                     | 8.2200                                                    | 8.1112                  | 7.4311                  |
| 90     | Chiripal Industries Ltd. (Fabric Division), Ahmedabad, Gujarat – 382405  | TXTOE090GJ          | 13116                                                    | 8.3568                                                    | 8.2444                  | 7.5410                  |
| 91     | Sangam Fashion Pvt. Ltd., Surat, Gujarat – 394315                        | TXTOE091GJ          | 5135                                                     | 10.8614                                                   | 10.6715                 | 9.4676                  |
| 92     | Aaiswarya Dyeing Mills Pvt. Ltd., Surat, Gujarat – 394327                | TXTOE092GJ          | 14482                                                    | 12.7311                                                   | 12.4702                 | 10.7995                 |
| 93     | Jindal Worldwide Ltd., Ahmedabad, Gujarat – 382445                       | TXTOE093GJ          | 8203                                                     | 13.0813                                                   | 12.8058                 | 11.0386                 |
| 94     | Sangam (India) Ltd., Processing Division, Bhilwara, Rajasthan – 311001   | TXTOE094RJ          | 17166                                                    | 3.5213                                                    | 3.5014                  | 3.3795                  |

---

## Sector: Textile

### Sub-Sector: Fibre

| S. No. | Obligated Entity (Name, Address and State)                                         | Registration Number | Baseline Equivalent Major Product Output 2023–24 (Tonne) | Baseline GHG Emission Intensity 2023–24 (tCO₂ eq / Tonne) | Compliance Year 2025–26 | Compliance Year 2026–27 |
| ------ | ---------------------------------------------------------------------------------- | ------------------- | -------------------------------------------------------- | --------------------------------------------------------- | ----------------------- | ----------------------- |
| 95     | DNH Spinners Pvt. Ltd., Surangi, Silvassa, Dadra & Nagar Haveli – 396230           | TXTOE095DN          | 222237                                                   | 0.3927                                                    | 0.3890                  | 0.2409                  |
| 96     | Kashi Vishwanath Textile Mill Pvt. Ltd., Kashipur, Uttarakhand – 244714            | TXTOE096UK          | 62924                                                    | 0.4499                                                    | 0.4456                  | 0.4191                  |
| 97     | Jiwarajka Textile Industries, Naroli, Silvassa, Dadra & Nagar Haveli – 396235      | TXTOE097DN          | 71610                                                    | 0.4989                                                    | –                       | 0.4647                  |
| 98     | Beekaylon Synthetics Pvt. Ltd., Masat, Silvassa, Dadra & Nagar Haveli – 396230     | TXTOE098DN          | 91089                                                    | 0.6150                                                    | –                       | 0.5729                  |
| 99     | Sanathan Textiles Pvt. Ltd., Surangi, Silvassa, Dadra & Nagar Haveli – 396230      | TXTOE099DN          | 240218                                                   | 0.6208                                                    | 0.6149                  | 0.5783                  |
| 100    | Madelin Enterprises Pvt. Ltd., Saily Road, Silvassa, Dadra & Nagar Haveli – 396230 | TXTOE100DN          | 146307                                                   | 0.6919                                                    | –                       | 0.6445                  |
| 101    | The Bombay Dyeing & Mfg. Co. Ltd., Patalganga, Maharashtra – 410220                | TXTOE101MH          | 141305                                                   | 0.7679                                                    | 0.7606                  | 0.7153                  |
| 102    | Filatex India Ltd., Dahej, Bharuch, Gujarat                                        | TXTOE102GJ          | 563992                                                   | 0.8204                                                    | 0.8126                  | 0.7642                  |
| 103    | Filatex India Ltd., Dadra & Nagar Haveli                                           | TXTOE103DN          | 57157                                                    | 0.8219                                                    | –                       | 0.7656                  |
| 104    | Madelin Enterprises Pvt. Ltd., Athola, Dadra & Nagar Haveli – 396230               | TXTOE104DN          | 105470                                                   | 0.8664                                                    | –                       | 0.8070                  |
| 105    | Reliance Industries Ltd., Hoshiarpur Manufacturing Division, Punjab                | TXTOE105PB          | 85003                                                    | 0.8545                                                    | 0.8464                  | 0.7959                  |
| 106    | Reliance Polyesters Ltd., Silvassa, Dadra & Nagar Haveli – 396230                  | TXTOE106DN          | 44277                                                    | 0.9990                                                    | –                       | 0.9306                  |
| 107    | Reliance Industries Ltd., Hazira Manufacturing Division, Surat, Gujarat            | TXTOE107GJ          | 777333                                                   | 1.0731                                                    | 1.0626                  | 1.0004                  |
| 108    | Unify Texturisers Pvt. Ltd., Silvassa, Dadra & Nagar Haveli – 396230               | TXTOE108DN          | 81309                                                    | 1.0276                                                    | –                       | 0.9572                  |
| 109    | Wellknown Polyesters Ltd., Daman – 396210                                          | TXTOE109DN          | 524557                                                   | 1.0654                                                    | 1.0552                  | 0.9924                  |
| 110    | Sanathan Textiles Pvt. Ltd., Unit II, Surangi, Dadra & Nagar Haveli                | TXTOE110DN          | 160093                                                   | 1.1197                                                    | –                       | 1.0430                  |
| 111    | Bhilosa Industries Pvt. Ltd., Naroli, Silvassa, Dadra & Nagar Haveli               | TXTOE111DN          | 620844                                                   | 1.1221                                                    | –                       | 1.0452                  |
| 112    | Raj Rayon Industries Ltd., Surangi, Silvassa, Dadra & Nagar Haveli                 | TXTOE112DN          | 52366                                                    | 1.2159                                                    | 1.2043                  | 1.1326                  |
| 113    | Perfect Filaments Ltd., Bhimpore, Daman                                            | TXTOE113DN          | 24896                                                    | 1.2538                                                    | 1.2418                  | 1.1679                  |
| 114    | Reliance Industries Ltd., Silvassa Manufacturing Division, Dadra & Nagar Haveli    | TXTOE114DN          | 378169                                                   | 1.2600                                                    | 1.2480                  | 1.1736                  |
| 115    | Bhilosa Industries Pvt. Ltd., Rakholi, Silvassa, Dadra & Nagar Haveli              | TXTOE115DN          | 248041                                                   | 1.3085                                                    | –                       | 1.2188                  |
| 116    | Indian Acrylics Ltd., Sangrur, Punjab – 148026                                     | TXTOE116PB          | 36194                                                    | 1.6137                                                    | 1.5983                  | 1.5031                  |
| 117    | Reliance Industries Ltd., Patalganga Manufacturing Division, Maharashtra – 410220  | TXTOE117MH          | 158832                                                   | 1.8453                                                    | 1.8277                  | 1.7189                  |
| 118    | Grasim Industries Ltd., Vilayat Industrial Estate, Bharuch, Gujarat – 392012       | TXTOE118GJ          | 513934                                                   | 2.2044                                                    | 2.1834                  | 2.0534                  |
| 119    | Birla Cellulosic, Kosamba, Bharuch, Gujarat – 394120                               | TXTOE119GJ          | 233723                                                   | 2.1868                                                    | 2.1659                  | 2.0370                  |
| 120    | Shriram Rayons, Kota, Rajasthan – 324004                                           | TXTOE120RJ          | 10036                                                    | 2.2239                                                    | 2.2027                  | 2.0716                  |
| 121    | Century Enka Ltd., Bhosari, Pune, Maharashtra – 411026                             | TXTOE121MH          | 23759                                                    | 2.4212                                                    | 2.3981                  | 2.2553                  |
| 122    | Grasilene Division, Grasim Industries Ltd., Kumarapatnam, Karnataka                | TXTOE122KA          | 101321                                                   | 2.7010                                                    | 2.6752                  | 2.5159                  |
| 123    | Pasupati Acrylon Ltd., Thakurdwara, Moradabad, Uttar Pradesh – 244601              | TXTOE123UP          | 35327                                                    | 3.0175                                                    | 2.9887                  | 2.8108                  |
| 124    | Grasim Industries Ltd., Birlagram Nagda, Ujjain, Madhya Pradesh – 456331           | TXTOE124MP          | 188930                                                   | 4.0359                                                    | 3.9974                  | 3.7594                  |
| 125    | Vardhman Acrylics Ltd., Jhagadia, Bharuch, Gujarat – 393110                        | TXTOE125GJ          | 19712                                                    | 3.6440                                                    | 3.6092                  | 3.3943                  |
| 126    | Grasim Industries Ltd. (Indian Rayon Unit), Veraval, Gujarat – 362266              | TXTOE126GJ          | 22193                                                    | 6.2006                                                    | 6.1414                  | 5.7758                  |
| 127    | Grasim Industries Ltd. – Century Rayon, Shahad, Thane, Maharashtra – 421103        | TXTOE127MH          | 26778                                                    | 9.4244                                                    | 9.3345                  | 8.7787                  |

---

## Sector: Textile

### Sub-Sector: Composite

| S. No. | Obligated Entity (Name, Address and State)                                      | Registration Number | Baseline Equivalent Major Product Output 2023–24 (Tonne) | Baseline GHG Emission Intensity 2023–24 (tCO₂ eq / Tonne) | Compliance Year 2025–26 | Compliance Year 2026–27 |
| ------ | ------------------------------------------------------------------------------- | ------------------- | -------------------------------------------------------- | --------------------------------------------------------- | ----------------------- | ----------------------- |
| 128    | Sri Krishna Spinning & Weaving Mills Pvt. Ltd., Bangalore, Karnataka – 560061   | TXTOE128KA          | 3400                                                     | 0.0900                                                    | –                       | 0.0900                  |
| 129    | Manomay Tex India Ltd., Gangrar, Chittorgarh, Rajasthan – 312901                | TXTOE129RJ          | 25108                                                    | 2.1680                                                    | –                       | 2.0195                  |
| 130    | Arvind Limited – Denim Business, Ahmedabad, Gujarat – 380025                    | TXTOE130GJ          | 27977                                                    | 2.3746                                                    | 2.3520                  | 2.2119                  |
| 131    | Maharaja Shree Umaid Mills Ltd., Pali, Rajasthan – 306401                       | TXTOE131RJ          | 1475                                                     | 2.4095                                                    | 2.3865                  | 2.2445                  |
| 132    | Super Gold Suitings Pvt. Ltd., Mandpiya, Bhilwara, Rajasthan – 311001           | TXTOE132RJ          | 10160                                                    | 2.8503                                                    | –                       | 2.6550                  |
| 133    | Ginni International Ltd., Neemrana, Alwar, Rajasthan – 301705                   | TXTOE133RJ          | 7942                                                     | 2.8542                                                    | 2.8270                  | 2.6587                  |
| 134    | Loyal Textile Mills Ltd., Kovilpatti, Tamil Nadu – 628501                       | TXTOE134TN          | 6051                                                     | 2.8639                                                    | 2.8366                  | 2.6677                  |
| 135    | Shahi Exports Pvt. Ltd., Shivamogga, Karnataka – 577222                         | TXTOE135KA          | 60897                                                    | 2.8917                                                    | –                       | 2.6936                  |
| 136    | Trident Ltd. (Home Textiles Division), Barnala, Punjab – 148107                 | TXTOE136PB          | 17024                                                    | 2.9520                                                    | 2.9238                  | 2.7498                  |
| 137    | Mohan Spintex India Ltd. (Unit III), Krishna, Andhra Pradesh – 521110           | TXTOE137AP          | 17901                                                    | 3.3766                                                    | 3.3444                  | 3.1453                  |
| 138    | Pee Vee Textiles Ltd., Wardha, Maharashtra – 442305                             | TXTOE138MH          | 33578                                                    | 3.5445                                                    | 3.5107                  | 3.3017                  |
| 139    | Premier Spinning & Weaving Mills Pvt. Ltd., Hosur, Tamil Nadu – 635124          | TXTOE139TN          | 2523                                                     | 3.6031                                                    | 3.5687                  | 3.3563                  |
| 140    | Tessitura Monti India Pvt. Ltd., Kolhapur, Maharashtra – 416202                 | TXTOE140MH          | 4578                                                     | 3.7210                                                    | 3.6855                  | 3.4661                  |
| 141    | Ultra Denim Pvt. Ltd., Surat, Gujarat – 394315                                  | TXTOE141GJ          | 10938                                                    | 3.9588                                                    | 3.9210                  | 3.6876                  |
| 142    | Surya Lakshmi Cotton Mills Ltd., Nagpur, Maharashtra                            | TXTOE142MH          | 14611                                                    | 3.9973                                                    | 3.9592                  | 3.7234                  |
| 143    | Pratibha Syntex Ltd., Pithampur, Madhya Pradesh – 454774                        | TXTOE143MP          | 2682                                                     | 4.0481                                                    | 4.0095                  | 3.7708                  |
| 144    | Welspun Living Ltd., Anjar, Kutch, Gujarat – 370110                             | TXTOE144GJ          | 105339                                                   | 5.8991                                                    | 5.8428                  | 5.4949                  |
| 145    | Maral Overseas Ltd., Khargone, Madhya Pradesh – 451660                          | TXTOE145MP          | 5049                                                     | 4.3378                                                    | 4.2964                  | 4.0407                  |
| 146    | Anubha Industries, Surat, Gujarat – 394315                                      | TXTOE146GJ          | 9103                                                     | 4.6948                                                    | 4.6500                  | 4.3732                  |
| 147    | BMD (P) Ltd., Banswara, Rajasthan – 327001                                      | TXTOE147RJ          | 4075                                                     | 5.3265                                                    | 5.2757                  | 4.9616                  |
| 148    | NSL Textiles Ltd., Guntur, Andhra Pradesh – 522233                              | TXTOE148AP          | 3526                                                     | 6.5780                                                    | 6.5152                  | 6.1273                  |
| 149    | RSWM Ltd. (Knitting Division), Banswara, Rajasthan – 327001                     | TXTOE149RJ          | 2395                                                     | 6.7669                                                    | 6.7023                  | 6.3033                  |
| 150    | Nitin Spinners Ltd., Begun, Chittorgarh, Rajasthan – 312023                     | TXTOE150RJ          | 9803                                                     | 6.9453                                                    | –                       | 6.4695                  |
| 151    | Himatsingka Linens, Hassan, Karnataka – 573201                                  | TXTOE151KA          | 36653                                                    | 6.9585                                                    | –                       | 6.4818                  |
| 152    | Raymond Zambaiti Ltd., Kolhapur, Maharashtra – 416216                           | TXTOE152MH          | 7309                                                     | 7.2040                                                    | 7.1353                  | 6.7105                  |
| 153    | Raymond Lifestyle Ltd., Valsad, Gujarat – 396185                                | TXTOE153GJ          | 9828                                                     | 7.3276                                                    | 7.2577                  | 6.8256                  |
| 154    | RSWM Ltd. (LNJ Denim Plant), Banswara, Rajasthan – 327001                       | TXTOE154RJ          | 19777                                                    | 7.5343                                                    | –                       | 7.0182                  |
| 155    | Raymond UCO Denim Pvt. Ltd., Yavatmal, Maharashtra – 445001                     | TXTOE155MH          | 14809                                                    | 7.6936                                                    | 7.6202                  | 7.1666                  |
| 156    | Vardhman Fabrics Ltd., Sehore, Madhya Pradesh – 466441                          | TXTOE156MP          | 26968                                                    | 7.7067                                                    | 7.6332                  | 7.1787                  |
| 157    | Valli Textile Mills, Sathur, Tamil Nadu – 626205                                | TXTOE157TN          | 3879                                                     | 7.8719                                                    | 7.7968                  | 7.3327                  |
| 158    | Donear Industries Ltd., Surat, Gujarat – 394304                                 | TXTOE158GJ          | 8906                                                     | 8.1790                                                    | 8.1010                  | 7.6186                  |
| 159    | Trident Ltd., Home Textile Division, Budhni, Madhya Pradesh – 466445            | TXTOE159MP          | 46662                                                    | 8.1934                                                    | 8.1152                  | 7.6321                  |
| 160    | Indo Count Industries Ltd., Valsad, Gujarat – 396105                            | TXTOE160GJ          | 13934                                                    | 8.4887                                                    | –                       | 7.9072                  |
| 161    | Arvind Products Ltd., Ahmedabad, Gujarat – 380022                               | TXTOE161GJ          | 4525                                                     | 8.8087                                                    | 8.7246                  | 8.2052                  |
| 162    | Bhaskar Industries Pvt. Ltd., Mandideep, Madhya Pradesh – 462046                | TXTOE162MP          | 16849                                                    | 9.1124                                                    | 9.0255                  | 8.4881                  |
| 163    | Welspun Living Ltd., Vapi, Gujarat – 396191                                     | TXTOE163GJ          | 29547                                                    | 9.8505                                                    | 9.7565                  | 9.1756                  |
| 164    | Grasim Industries Ltd., Jayashree Textiles, Rishra, West Bengal – 712249        | TXTOE164WB          | 2457                                                     | 10.0724                                                   | 9.9763                  | 9.3823                  |
| 165    | RSWM Ltd., Chhata, Mathura, Uttar Pradesh – 281401                              | TXTOE165UP          | 2633                                                     | 10.4900                                                   | 10.3899                 | 9.7713                  |
| 166    | NSL Textiles Ltd., Prakasam, Andhra Pradesh – 523167                            | TXTOE166AP          | 2528                                                     | 11.2958                                                   | 11.1880                 | 10.5219                 |
| 167    | Grasim Bhiwani Textiles Ltd., Bhiwani, Haryana – 127021                         | TXTOE167HR          | 5126                                                     | 13.1303                                                   | 13.0050                 | 12.2307                 |
| 168    | Reliance Industries Ltd., Textile Division, Naroda, Ahmedabad, Gujarat – 382330 | TXTOE168GJ          | 4307                                                     | 13.9924                                                   | 13.8589                 | 13.0338                 |
| 169    | Raymond Lifestyle Ltd., Chhindwara, Madhya Pradesh                              | TXTOE169MP          | 4446                                                     | 15.3324                                                   | 15.1861                 | 14.2819                 |
| 170    | Nandan Denim Pvt. Ltd., Ahmedabad, Gujarat – 380007                             | TXTOE170GJ          | 14323                                                    | 16.5986                                                   | 16.4402                 | 15.4614                 |
| 171    | GM Fabrics Pvt. Ltd., Boisar, Maharashtra – 401506                              | TXTOE171MH          | 1744                                                     | 16.6943                                                   | 16.5350                 | 15.5505                 |
| 172    | Arvind Ltd., Khatraj, Gandhinagar, Gujarat – 382721                             | TXTOE172GJ          | 37761                                                    | 16.7463                                                   | 16.5865                 | 15.5990                 |
| 173    | Mafatlal Industries Ltd., Nadiad Unit, Gujarat – 387001                         | TXTOE173GJ          | 6194                                                     | 17.4268                                                   | 17.2605                 | 16.2329                 |

---



